# Try to keep each section sorted alphabetically (with some exceptions to group entries together)
[versions]
autoService = "1.0.1"

# Versions used by build-logic
googleJavaFormat = "1.14.0"
ktlint = "0.44.0"

[libraries]
autoService = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
autoService-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
compileTesting = "com.google.testing.compile:compile-testing:0.19"
junit = "junit:junit:4.13.2"
truth = "com.google.truth:truth:1.1.3"

# Used in below bundle
errorprone-core = "com.google.errorprone:error_prone_core:2.11.0"
nullaway = "com.uber.nullaway:nullaway:0.9.5"

[bundles]
# Used by build-logic
errorprone = [ "errorprone-core", "nullaway" ]

[plugins]
errorprone = "net.ltgt.errorprone:2.0.2"
nullaway = "net.ltgt.nullaway:1.3.0"
spotless = "com.diffplug.spotless:6.3.0"
